### ISSUE TITLE
TODO in Jan 2025: Deprecated flag `color_mode` used in MQTT JSON light config

### ISSUE THREAD

**Issue by andyblac** [wez/govee2mqtt#164]
### Govee Device SKU

H61A8

### Govee2MQTT Version

2024.01.24-ea3cd430

### Describe the issue

Error in HA logs after a startup

### Startup Diagnostics

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=core-mosquitto
GOVEE_TEMPERATURE_SCALE=C
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_LAN_BROADCAST_ALL=true
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-04-02T11:40:57 INFO  govee::commands::serve] Starting service. version 2024.01.24-ea3cd430
[2024-04-02T11:40:57 INFO  govee::commands::serve] Querying platform API for device list
[2024-04-02T11:40:58 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-04-02T11:41:00 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-04-02T11:41:00 INFO  govee::commands::serve] Starting LAN discovery
[2024-04-02T11:41:00 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-04-02T11:41:00 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-04-02T11:41:10 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-04-02T11:41:10 INFO  govee::commands::serve] Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8)
[2024-04-02T11:41:10 INFO  govee::commands::serve]   LAN API: ip=192.168.3.27
[2024-04-02T11:41:10 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-04-02T11:41:10 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-04-02T11:41:10 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
[2024-04-02T11:41:10 INFO  govee::commands::serve]   Quirk { sku: "H61A8", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }
[2024-04-02T11:41:10 INFO  govee::commands::serve] 
[2024-04-02T11:41:10 INFO  govee::commands::serve] H5075_4D3D (4D:C8:A4:C1:38:EA:4D:3D H5075)
[2024-04-02T11:41:10 INFO  govee::commands::serve]   Undoc: room=None supports_iot=false ble_only=true
[2024-04-02T11:41:10 WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.
[2024-04-02T11:41:10 INFO  govee::commands::serve] 
[2024-04-02T11:41:10 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-04-02T11:41:16 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-02T11:41:17 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-04-02T11:41:48 INFO  govee::service::hass] Home Assistant status changed: online
[2024-04-02T11:41:48 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-02T12:30:03 WARN  govee::cache] request https://openapi.api.govee.com/router/api/v1/device/scenes status 500: Internal Server Error. Response body: {"timestamp":"2024-04-02T11:30:03.038+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/device/scenes"}, will use prior results
[2024-04-02T12:30:03 WARN  govee::cache] request https://openapi.api.govee.com/router/api/v1/device/diy-scenes status 500: Internal Server Error. Response body: {"timestamp":"2024-04-02T11:30:03.695+00:00","status":500,"error":"Internal Server Error","path":"/api/v1/device/diy-scenes"}, will use prior results
[2024-04-02T20:22:39 INFO  govee::service::hass] Command for Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8): {"state":"OFF"}
[2024-04-02T20:22:39 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) light power state
[2024-04-03T08:26:20 INFO  govee::service::hass] Command for Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8): {"state":"OFF"}
[2024-04-03T08:26:20 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) light power state
[2024-04-03T18:03:12 INFO  govee::service::hass] Command for Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8): {"state":"OFF"}
[2024-04-03T18:03:12 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) light power state
[2024-04-03T20:24:34 INFO  govee::service::hass] Command for Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8): {"state":"OFF"}
[2024-04-03T20:24:34 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) light power state
[2024-04-04T08:29:19 INFO  govee::service::hass] Command for Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8): {"state":"OFF"}
[2024-04-04T08:29:19 INFO  govee::service::state] Using LAN API to set Back Garden Neon Rope (11:CB:36:35:30:0B:77:FF H61A8) light power state
[2024-04-04T12:56:59 INFO  govee::service::hass] Home Assistant status changed: offline
[2024-04-04T12:57:02 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-04T12:57:42 INFO  govee::service::hass] Home Assistant status changed: online
[2024-04-04T12:57:42 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-04T13:03:25 INFO  govee::service::hass] Home Assistant status changed: offline
[2024-04-04T13:03:25 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-04T13:03:48 INFO  govee::service::hass] Home Assistant status changed: online
[2024-04-04T13:03:48 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-04T13:25:22 INFO  govee::service::hass] Home Assistant status changed: offline
[2024-04-04T13:25:24 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
[2024-04-04T13:25:47 INFO  govee::service::hass] Home Assistant status changed: online
[2024-04-04T13:25:47 INFO  govee::service::hass] Wait 1.1s for hass to settle on 22 entity configs
```

### Home Assistant Logs

```
Logger: homeassistant.components.mqtt.light.schema_json
Source: components/mqtt/light/schema_json.py:157
integration: MQTT (documentation, issues)
First occurred: 13:25:31 (19 occurrences)
Last logged: 13:25:47

Deprecated flag `color_mode` used in MQTT JSON light config , the `color_mode` flag is not used anymore and should be removed. Got: {'availability_topic': 'gv2mqtt/availability', 'name': 'Segment 011', 'origin': {'name': 'gv2mqtt', 'sw_version': '2024.01.24-ea3cd430', 'support_url': 'https://github.com/wez/govee2mqtt'}, 'device': {'name': 'Back Garden Neon Rope', 'manufacturer': 'Govee', 'model': 'H61A8', 'via_device': 'gv2mqtt', 'identifiers': ['gv2mqtt-11CB3635300B77FF']}, 'unique_id': 'gv2mqtt-11CB3635300B77FF-10', 'schema': 'json', 'command_topic': 'gv2mqtt/light/11CB3635300B77FF/command/10', 'state_topic': 'gv2mqtt/light/11CB3635300B77FF/state/10', 'optimistic': True, 'supported_color_modes': ['rgb'], 'color_mode': True, 'brightness': True, 'brightness_scale': 100, 'effect': True, 'payload_available': 'online', 'platform': 'mqtt'}. This will stop working in Home Assistant Core 2025.3
Deprecated flag `color_mode` used in MQTT JSON light config , the `color_mode` flag is not used anymore and should be removed. Got: {'availability_topic': 'gv2mqtt/availability', 'name': 'Segment 012', 'origin': {'name': 'gv2mqtt', 'sw_version': '2024.01.24-ea3cd430', 'support_url': 'https://github.com/wez/govee2mqtt'}, 'device': {'name': 'Back Garden Neon Rope', 'manufacturer': 'Govee', 'model': 'H61A8', 'via_device': 'gv2mqtt', 'identifiers': ['gv2mqtt-11CB3635300B77FF']}, 'unique_id': 'gv2mqtt-11CB3635300B77FF-11', 'schema': 'json', 'command_topic': 'gv2mqtt/light/11CB3635300B77FF/command/11', 'state_topic': 'gv2mqtt/light/11CB3635300B77FF/state/11', 'optimistic': True, 'supported_color_modes': ['rgb'], 'color_mode': True, 'brightness': True, 'brightness_scale': 100, 'effect': True, 'payload_available': 'online', 'platform': 'mqtt'}. This will stop working in Home Assistant Core 2025.3
Deprecated flag `color_mode` used in MQTT JSON light config , the `color_mode` flag is not used anymore and should be removed. Got: {'availability_topic': 'gv2mqtt/availability', 'name': 'Segment 013', 'origin': {'name': 'gv2mqtt', 'sw_version': '2024.01.24-ea3cd430', 'support_url': 'https://github.com/wez/govee2mqtt'}, 'device': {'name': 'Back Garden Neon Rope', 'manufacturer': 'Govee', 'model': 'H61A8', 'via_device': 'gv2mqtt', 'identifiers': ['gv2mqtt-11CB3635300B77FF']}, 'unique_id': 'gv2mqtt-11CB3635300B77FF-12', 'schema': 'json', 'command_topic': 'gv2mqtt/light/11CB3635300B77FF/command/12', 'state_topic': 'gv2mqtt/light/11CB3635300B77FF/state/12', 'optimistic': True, 'supported_color_modes': ['rgb'], 'color_mode': True, 'brightness': True, 'brightness_scale': 100, 'effect': True, 'payload_available': 'online', 'platform': 'mqtt'}. This will stop working in Home Assistant Core 2025.3
Deprecated flag `color_mode` used in MQTT JSON light config , the `color_mode` flag is not used anymore and should be removed. Got: {'availability_topic': 'gv2mqtt/availability', 'name': 'Segment 014', 'origin': {'name': 'gv2mqtt', 'sw_version': '2024.01.24-ea3cd430', 'support_url': 'https://github.com/wez/govee2mqtt'}, 'device': {'name': 'Back Garden Neon Rope', 'manufacturer': 'Govee', 'model': 'H61A8', 'via_device': 'gv2mqtt', 'identifiers': ['gv2mqtt-11CB3635300B77FF']}, 'unique_id': 'gv2mqtt-11CB3635300B77FF-13', 'schema': 'json', 'command_topic': 'gv2mqtt/light/11CB3635300B77FF/command/13', 'state_topic': 'gv2mqtt/light/11CB3635300B77FF/state/13', 'optimistic': True, 'supported_color_modes': ['rgb'], 'color_mode': True, 'brightness': True, 'brightness_scale': 100, 'effect': True, 'payload_available': 'online', 'platform': 'mqtt'}. This will stop working in Home Assistant Core 2025.3
Deprecated flag `color_mode` used in MQTT JSON light config , the `color_mode` flag is not used anymore and should be removed. Got: {'availability_topic': 'gv2mqtt/availability', 'name': 'Segment 015', 'origin': {'name': 'gv2mqtt', 'sw_version': '2024.01.24-ea3cd430', 'support_url': 'https://github.com/wez/govee2mqtt'}, 'device': {'name': 'Back Garden Neon Rope', 'manufacturer': 'Govee', 'model': 'H61A8', 'via_device': 'gv2mqtt', 'identifiers': ['gv2mqtt-11CB3635300B77FF']}, 'unique_id': 'gv2mqtt-11CB3635300B77FF-14', 'schema': 'json', 'command_topic': 'gv2mqtt/light/11CB3635300B77FF/command/14', 'state_topic': 'gv2mqtt/light/11CB3635300B77FF/state/14', 'optimistic': True, 'supported_color_modes': ['rgb'], 'color_mode': True, 'brightness': True, 'brightness_scale': 100, 'effect': True, 'payload_available': 'online', 'platform': 'mqtt'}. This will stop working in Home Assistant Core 2025.3
```

**Comment by wez** [comment]
Thanks for the info. I won't "fix" this until closer to 2025; removing this option will break earlier versions of home assistant and there needs to be sufficient time for folks to upgrade to whatever version you are running (please share that info!)

**Comment by andyblac** [comment]
> Thanks for the info. I won't "fix" this until closer to 2025; removing this option will break earlier versions of home assistant and there needs to be sufficient time for folks to upgrade to whatever version you are running (please share that info!)

started in HA: 2024.04

**Comment by andersonvom** [comment]
Hi @wez! Based on the MR that introduced the deprecation warning (https://github.com/home-assistant/core/pull/111676), it seems that the flag was/is already not being used:

> The `color_mode` flag is not used anymore, and should be removed. Instead `supported_color_modes` is checked. If it is not set, then the `color_temp`, `hs`, `rgb`,  and `xy` flags will still be evaluated.

Since `supported_color_modes` has been in place since 2021.5.4 (https://github.com/home-assistant/core/pull/50627), and `govee2mqtt` has been using it from the beginning ([`src/service/hass.rs` @ b517830cc2][1]), it looks like this is already safe to remove.

[1]: https://github.com/wez/govee2mqtt/blob/b517830cc208c250030f3af10f0e4f96b1992106/src/service/hass.rs

**Comment by dougmaitelli** [comment]
It seems like this is now straight up throwing errors in HA.

**Comment by wez** [comment]
FWIW, this was fixed in 8029cb5d7dd9b3ff7ee5ee2a161be97f9ca428ca, if you're seeing errors around this, you're probably running an older version and need to upgrade

**Comment by andersonvom** [comment]
@wez I think there's an issue with the `latest` docker image as I was still seeing this despite running `ghcr.io/wez/govee2mqtt:latest`. The only way I was able to get the fix that had been merged was by running a specific commit hash tag (e.g. `ghcr.io/wez/govee2mqtt:2025.01.04-2c39a50f`).

**Comment by dougmaitelli** [comment]
Yeah, I can confirm I have the latest version installed as an addon and the issue is still there, everything works but the error shows in logs.

Unless this is coming from somewhere else, because in the logs the error is thrown by the MQTT component without much origin context.

**Comment by turboc1208** [comment]
any progress on this.  running version Current version: 2025.11.25-60a39bcc as an addon.
